// Code generated by generate-boot-hashes.sh - DO NOT EDIT

package verification

// ExpectedFileHashes contains SHA256 hashes of critical boot files
// These are verified at startup to detect tampering
// Generated during build from known boot file artifacts
var ExpectedFileHashes = map[string]string{
    "config.txt": "f74f6f93cd50680bd0bf14425e5182923b81e45f390f64958f2c9b1faeb88ed7",
    "start4x.elf": "c30fbdfedad7180245ff567ccdea953fc1816d0da3ff4701b15071c6f8b47a89",
    "cmdline.txt": "b2c3d4f97d25da58f90e02eeb6d6d6846f1d652bd0e0d8ae295204f31175817b",
    "Image.gz": "d0065cd62b768fe9ad4c5c84ea49704539be55d428453ef0087e5358e87a70d3",
    "bootcode.bin": "af603ebd97e7b692c30195563f7b25656eb05d57838cf1a715ebb470d1614ce4",
    "fixup4x.dat": "41328f6587c0cd47ae7fa7edab4bf62730dda54caf52ffaa3bfb24ff93b8348b",
}
